kind: pipeline
name: docker

steps:
- name: publish
  image: plugins/docker:17.12
  settings:
    repo: mediatekcloud/simulator
    auto_tag: true
    cache_from: mediatekcloud/simulator
    dockerfile: Dockerfile
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    event:
    - push
    - tag
